version: '3.5'
services:
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass de2816bd9c1a5d7534a0f486fa7b8c80
    restart: unless-stopped
    volumes:
      - redis_data:/data
  mongodb:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: jschan
      MONGO_INITDB_ROOT_PASSWORD: ce34badea44bb7040934fdc2b7994ac2
    volumes:
      - mongodb_data:/data/db
  jschan:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '7000:7000'
    environment:
      NODE_ENV: production
      NO_CAPTCHA: '1'
      MONGO_USERNAME: jschan
      MONGO_PASSWORD: ce34badea44bb7040934fdc2b7994ac2
      REDIS_PASSWORD: de2816bd9c1a5d7534a0f486fa7b8c80
      MONGO_HOST: mongodb
      REDIS_HOST: redis
      COOKIE_SECRET: 94d3162a863dceabab6b0b2fd514cd26da2fdf087ad154757d9a981f028a29bf
      TRIPCODE_SECRET: 3e128988bb9f9d7edbc74d542e573ffd13c221c92f5b761964c31e9ab14912be
      IP_HASH_SECRET: 64258418bea7010f5ee702a21f843e01e2871b99027628a854f870c4f495f669
      POST_PASSWORD_SECRET: 21e37f4df93621c2895f2f9135a0ac433230270bf499acf79ac2e34ba5ae7f7e
    depends_on:
      - redis
      - mongodb
volumes:
  mongodb_data: null
  redis_data: null